### ISSUE TITLE
READMEのDocumentation項目の削除提案

### ISSUE THREAD

**Issue by siromath** [takamoso/tatami#2]
公式ドキュメント([https://tatami.codes/docs/installation/](https://tatami.codes/docs/installation/))にDocumentationがあるため、READMEには不要なのではないか、という提案です。
ご検討のほどよろしくお願いいたします。

**Comment by takamoso** [comment]
README.mdすっかり放置してしまっていました。

READMEをなくすか、最低限の紹介文等を書いておくかで悩んでいます。

**Comment by siromath** [comment]
確かにインストールなどの項目も公式ドキュメントにあるので、README自体いらないかもしれませんね。
最低限の説明を書きつつ、公式ドキュメントへのリンクを張るくらいでも良いかと思います。
